### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by rabbiveesh** [houseabsolute/DateTime.pm#102]
I just installed DateTime in a fresh perlbrew env, and it failed b/c it was missing Class::Singleton and Class::Data::Inheritable.

I'm not sure how that slipped its way out of the dependency chain, or if there's something messed up with my setup.

**Comment by autarch** [comment]
Neither of those are dependencies for `DateTime`. `Class::Singleton` is required by DateTime::TimeZone. `Class::Data::Inheritable` is a dependency of `Exception::Class`.

I can't even guess at what happened with your install without logs of exactly what you did to install it in the first place. I'm going to close this issue, but if you have more information, please add it and I can reopen the issue if necessary.
