### ISSUE TITLE
DateTime->now not using Time:HiRes::time if imported

### ISSUE THREAD

**Issue by blmatthews** [houseabsolute/DateTime.pm#105]
Should these work the same?

$ perl -MTime::HiRes=time -MDateTime -e'print DateTime->now()->strftime("%N%n")'
000000000
$ perl -MTime::HiRes=time -MDateTime -e'print DateTime->from_epoch(epoch=>time)->strftime("%N%n")'
721470000

(I ran them multiple times so I didn't just get stunningly (un?)lucky on the ->now() version :-) )

**Comment by autarch** [comment]
When you import `time` from `Time::HiRes` it changes calls to `time` in the package where you imported it. When you call `DateTime->now` the `time` call happens in the `DateTime` package, not the one where you imported it. You might find [`DateTime::HiRes`](https://metacpan.org/release/DateTime-HiRes) helpful if you always want a subsecond time from `->now`.
