### ISSUE TITLE
Can not find a way to stringify DateTime object using ->format_timestamptz

### ISSUE THREAD

**Issue by KES777** [houseabsolute/DateTime.pm#110]
At [the section](https://metacpan.org/pod/DateTime#Formatters-And-Stringification) I can see how to set formatter.
But how to switch function `->stringify` to use `->format_timestamptz`? Please document this

Otherwise I lose useful info

```
DBG> $DB::z->ctime
DateTime 2019-04-16T14:42:51

DBG> $DB::z
HyperMouse::Schema::Result::Order {
  _column_data => {
    agreement_id => 1549,
    app_period => [-infinity,"2020-03-01 00:00:00+02"),
    billed_to => 2020-03-01 00:00:00+02,
    comment => этот,
    ctime => 2019-04-16 14:42:51.27893+03,
    docdate => 2016-04-01,
    docn => 201322,
    domain_uuid => undef,
    id => 10779,
    package_id => 185,
    period_id => 10,
    service_level_id => 1,
    suma => 0.000000000000000000,
    vm_id => undef,
  },
  _in_storage => 1,
  _inflated_column => {
    ctime => DateTime 2019-04-16T14:42:51,
  },
  _result_source => IGNORED,
}

DBG> $DB::z->ctime->{ tz }
DateTime::TimeZone::OffsetOnly {
  name => +0300,
  offset => 10800,
}

DBG>
```

**Comment by autarch** [comment]
There's no way to do this directly, but you could always subclass or wrap a formatter class and provide your own `format_datetime` method that does whatever you want.

**Comment by KES777** [comment]
I can not subclass. DBIx::Class uses `DateTime` while inflating =(

**Comment by autarch** [comment]
DBIx::Class lets you control which classes to use for inflation. I'm sure you could have it use a different class. I haven't used DBIC recently though, so I can't remember exactly how to do this.
