### ISSUE TITLE
Implement `use DateTime ':hires'`

### ISSUE THREAD

**Issue by KES777** [houseabsolute/DateTime.pm#111]
I can not find in documentation a switch that makes

     $dt = DateTime->now; # same as ( epoch => time() )

to work:

    $dt = DateTime->now; # same as ( epoch => Time::HiRes::time() )

I suppose it could be enabled as:

    use DateTime ':hires';

or, probably, :

    $dt = DateTime->now( 'hires' )

**Comment by autarch** [comment]
I think you want https://metacpan.org/pod/DateTime::HiRes.

You can also pass a hi-res time to DateTime->from_epoch:

```perl
use Time::Hires qw( time );

say DateTime->from_epoch( epoch => time );
```

That should just work.

A doc patch to mention both of these options would be great!
