### ISSUE TITLE
Add ability to lock/unlock DateTime objects through methods, which when locked causes an exception on in-place modification

### ISSUE THREAD

**Issue by kbenson** [houseabsolute/DateTime.pm#118]
The idea is fairly simple, a way to flag DateTime objects as not allowing modification, so if you're passing them around, if they are accidentally modified deep within some deep call stack, it's an error/exception rather than silent bug.

e.g.
```
my $dt = DateTime->now->lock;
# ... later somewhere deeper in the code where we've passed $dt through as a param maybe a few times
my $new_dt = $dr->add(days=>1); # Boom!
```

If this is something acceptable to the module, I'm willing to implement and submit a pull request, but I don't want to waste the time if it's not seen as worthwhile.

**Comment by autarch** [comment]
This is an interesting idea but I'm not sure it belongs in the DateTime package. If you want a never-allowed-to-mutate DateTime there's already [DateTime::Moonpig](https://metacpan.org/pod/DateTime::Moonpig). If you want a sometimes-mutable DateTime I'd suggest writing a similar subclass that implements this and releasing it to CPAN.

**Comment by kbenson** [comment]
Fair enough.  I suspected there might be reasons why it was considered undesirable, which is why I asked before doing the actual work.  I'll look into implementing it as a subclass, which should also be fairly easy.  Thanks for your consideration. :)
