### ISSUE TITLE
Have from_epoch() support just getting seconds passed

### ISSUE THREAD

**Issue by neilb** [houseabsolute/DateTime.pm#119]
It feels like more often than not, when I have epoch seconds and want a DateTime,
I write something like this:

    $dt = DateTime->from_epoch( time() );

Then I get the error message, say "D'oh!", and add the `epoch => `

The `"epoch"` parameter feels redundant, and I can't be the only one who does this? How about supporting both styles?

**Comment by autarch** [comment]
Yes, I think this would be possible. We'd need to check that `@_ == 1` and that `$_[0]` is a valid `Num`. Are you up for writing a PR?

**Comment by neilb** [comment]
> Are you up for writing a PR?

My first thought was "yeah", that should be easy &mdash; as you say,we just need to check @_ and valid number. How hard can that be? Then I looked at the code for `from_epoch` with its validation etc, and remembering there are other options allowed, so it's not such a quick fix, for me at least.

I've put it on my perl todo list, but TBH there are a lot of things ahead of it, so realistically not likely to happen any time soon, sadly.

**Comment by danstewart** [comment]
@autarch I've had a look at this but can't figure out how to validate with `Params::ValidationCompiler`, any pointers?

This seems to work:
```perl
my %p     = $_[0] =~ /^\d+$/ ? ( epoch => $_[0] ) : $validator->(@_);
```

Is there a smart way to work this into the current validator that I'm missing, or is it possible to have the validator not die, then I could use two separate validators?

**Comment by autarch** [comment]
#123

**Comment by autarch** [comment]
Added in 1.56
