### ISSUE TITLE
DateTime->from_epoch( epoch => 0 )

### ISSUE THREAD

**Issue by jackdeguest** [houseabsolute/DateTime.pm#126]
If one creates an instance of DateTime such as `my $dt = DateTime->from_epoch( epoch => 0, time_zone => 'Asia/Tokyo' )` and then switch to GMT `$dt->set_time_zone( 'GMT' )`, the resulting datetime string will still be `1970-01-01T00:00:00` whereas it ought to be `1969-12-31T15:00:00`

I understand from the documentation that "[b]y default, the returned object will be in the UTC time zone.", however, the `time_zone` parameter was provided. Thus it seems that DateTime starts off setting a datetime object with the epoch value, but based on UTC and then after change the time zone, here in our example, to Asia/Tokyo.

If one does:

```
my $dt2 = DateTime->new(
    year => 1970,
    month => 1,
    day => 1,
    hour => 0,
    minute => 0,
    second => 0,
    time_zone => 'local'
);
$dt2->set_time_zone( 'GMT' );
```

then, the result would correctly be `1969-12-31T15:00:00`

In the former, example, I think either the code needs to be updated to instantiate the datetime object with the time zone provided, thus yielding `1969-12-31T15:00:00` or the documentation should be amended to reflect that any `time_zone` argument passed will be applied after the initial object has been created, thus making the date time to `1970-01-01T09:00:00`

**Comment by autarch** [comment]
This works as expected:

```perl
use v5.30;

use DateTime;
my $dt = DateTime->new(
    year      => 1970,
    month     => 1,
    day       => 1,
    hour      => 0,
    minute    => 0,
    second    => 0,
    time_zone => 'Asia/Tokyo'
);
say $dt;
$dt->set_time_zone('GMT');
say $dt;
```

```
$> perl ./foo 
1970-01-01T00:00:00
1969-12-31T15:00:00
```

I'm pretty sure your machine's local time zone is set to UTC, not Asia/Tokyo.

**Comment by autarch** [comment]
You can use this to see what `DateTime::TimeZone` thinks your machine's local zone is:

```
perl -MDateTime -E "say DateTime->now(time_zone => 'local')->time_zone->name"
```

**Comment by jackdeguest** [comment]
The result for `perl -MDateTime -E "say DateTime->now(time_zone => 'local')->time_zone->name"` yields on my machine `Asia/Tokyo`

You use DateTime->new passing it a list of argument whereas I reported the bug using `DateTime->from_epoch8 epoch => 0, time_zone => "Asia/Tokyo" )` which is different.
I agree the former works as expected, but not the latter.

**Comment by autarch** [comment]
Ah, I see. I didn't read your original report carefully enough. I didn't see that the second example was working as you expected.

So the code is working as intended, but I agree the documentation is unclear. I will make some tweaks.

**Comment by autarch** [comment]
This change was in the 1.55 release.
