### ISSUE TITLE
datetime.perl.org not found

### ISSUE THREAD

**Issue by jkeenan** [houseabsolute/DateTime.pm#130]
Today I had occasion for the first time in a long time to consult the DateTime documentation.  I read:
```
For details on this project please see <http://datetime.perl.org/>. 
The DateTime site has a FAQ which may help answer many 
"how do I do X?" questions. The FAQ is at 
<http://datetime.perl.org/wiki/datetime/page/FAQ>.
```
However, my browser immediately responded: *We can’t connect to the server at datetime.perl.org.*

I got the same result using `https` in the URL.

What has happened to this website?

**Comment by autarch** [comment]
The site is long gone. I removed all the references to it from the docs but I haven't done a release since then. I'll make a new release now since there's a bunch of doc fixes ready to go.
