### ISSUE TITLE
Europe/Dublin DST flag is backwards?

### ISSUE THREAD

**Issue by bbkr** [houseabsolute/DateTime.pm#136]
First correct behavior of Europe time zone using DST of `Europe/London`:
```
perl -E 'use DateTime; my $dt = DateTime->new( "year" => 2022, "month" => 10, "day" => 30, "hour" => 0, "time_zone" => "Europe/London" ); for (1..6) { say $dt, " is_dst=", $dt->is_dst; $dt->add( "hours" => 1 ) }'
2022-10-30T00:00:00 is_dst=1
2022-10-30T01:00:00 is_dst=1
2022-10-30T01:00:00 is_dst=0   # 2:00 became 1:00
2022-10-30T02:00:00 is_dst=0
2022-10-30T03:00:00 is_dst=0
2022-10-30T04:00:00 is_dst=0
```

Now let's take a look at `Europe/Dublin`:
```
$ perl -E 'use DateTime; my $dt = DateTime->new( "year" => 2022, "month" => 10, "day" => 30, "hour" => 0, "time_zone" => "Europe/Dublin" ); for (1..6) { say $dt, " is_dst=", $dt->is_dst; $dt->add( "hours" => 1 ) }'
2022-10-30T00:00:00 is_dst=0
2022-10-30T01:00:00 is_dst=0
2022-10-30T01:00:00 is_dst=1    # 2:00 became 1:00
2022-10-30T02:00:00 is_dst=1
2022-10-30T03:00:00 is_dst=1
2022-10-30T04:00:00 is_dst=1
```

It **gained** DST flag while setting clock **back**???

**Comment by bbkr** [comment]
https://github.com/houseabsolute/DateTime-TimeZone/issues/41 - Looks like this was already discovered. And comment says it all: "that matches the law, not sanity".

**Comment by n1vux** [comment]
On Wed, Oct 19, 2022, 11:19 Pawel Pabian ***@***.***> wrote:

> houseabsolute/DateTime-TimeZone#41
> <https://github.com/houseabsolute/DateTime-TimeZone/issues/41> - Looks
> like this was already discovered. And comment says it all: "that matches
> the law, not sanity"
>

Yes!

Thus, assuming the boolean DST flag means offset in one direction is only
usually correct;  one must check the offset to be certain, every time.

(So inference on the other Dublin issue #135 might still be correct)
