### ISSUE TITLE
Clarify pod "our $App::LocalTZ = ..." (not legal Perl syntax)

### ISSUE THREAD

**Issue by jimav** [houseabsolute/DateTime.pm#137]
The pod contains this suggested code:

   `our $App::LocalTZ = DateTime::TimeZone->new( name => 'local' );`

which is not valid Perl code (gets "No package name allowed for variable $App::LocalTZ in "our" at...")

Suggest replacing this with an example which is valid syntax.

**Comment by autarch** [comment]
I fixed this a while back in the repo and recent releases have the fix. Thansk!
