### ISSUE TITLE
Sub::Identify not being detected as a prerequisite

### ISSUE THREAD

**Issue by sisyphus** [houseabsolute/DateTime.pm#140]
On Windows, <code>cpan -i DateTime</code> fails to install the module unless <code>Sub::Identify</code> has been previously installed.
In the absence of <code>Sub::Identify</code>, the 'make test' step becomes very slow and very noisy, with a few tests failing
Thankfully, amongst all of the noise we see a number of <code>Can't locate Sub/Identify.pm in @INC...</code> warnings - and it turns out that this issue is resolved by installing <code>Sub::Identify</code>.

I guess that <code>Sub::Identify</code> is required only for testing.
I haven't checked to see whether this issue affects systems other than Windows.

Cheers,
Rob

**Comment by autarch** [comment]
Can you paste the entire error here? `Sub::Identify` is _not_ a direct prereq of DateTime, so I suspect the error lies somewhere up the dependency chain.

**Comment by autarch** [comment]
FWIW I was able to install DateTime using `cpan -i DateTime` on a fresh Perl 5.38.0 on Linux, so this might be a Windows-specific thing somewhere in the dep chain (but again, I don't think the issue is with DateTime itself).

**Comment by autarch** [comment]
Looking at https://cpandeps.grinnz.com/?dist=DateTime&dist_version=&phase=runtime&perl_version=v5.36.0&style=auto I'd guess the issue is with `namespace::autoclean`.

**Comment by sisyphus** [comment]
> ... I suspect the error lies somewhere up the dependency chain

Aaah, yes. I think you're right.
Here's what I see (repeated ad nauseam) when Sub::Identify is missing:
<code>A scope-end callback raised an exception, which can not be propagated when B::Hooks::EndOfScope operates in pure-perl mode. Your program will CONTINUE EXECUTION AS IF NOTHING HAPPENED AFTER THIS WARNING. Below is the complete exception text, followed by a stack-trace of the callback execution:

Can't locate Sub/Identify.pm in @INC (you may need to install the Sub::Identify module) (@INC entries checked: D:\s\DateTime\blib\lib D:\s\DateTime\blib\arch C:/perl-5.38.0-1310-lhm/site/lib/MSWin32-x86-multi-thread-64int-quadmath C:/perl-5.38.0-1310-lhm/site/lib C:/perl-5.38.0-1310-lhm/lib/MSWin32-x86-multi-thread-64int-quadmath C:/perl-5.38.0-1310-lhm/lib .) at C:/perl-5.38.0-1310-lhm/site/lib/namespace/autoclean.pm line 200.

 at C:/perl-5.38.0-1310-lhm/site/lib/B/Hooks/EndOfScope/PP.pm line 36.
        B::Hooks::EndOfScope::PP::__invoke_callback(CODE(0x2efb174)) called at C:/perl-5.38.0-1310-lhm/site/lib/B/Hooks/EndOfScope/PP/FieldHash.pm line 31
        B::Hooks::EndOfScope::PP::_TieHintHashFieldHash::DELETE(B::Hooks::EndOfScope::PP::_TieHintHashFieldHash=HASH(0x2e2ef24), 49262748) called at D:\s\DateTime\blib\lib/DateTime/Types.pm line 161
        require DateTime/Types.pm called at D:\s\DateTime\blib\lib/DateTime/Duration.pm line 12
        DateTime::Duration::BEGIN() called at D:\s\DateTime\blib\lib/DateTime/Duration.pm line 12
        eval {...} called at D:\s\DateTime\blib\lib/DateTime/Duration.pm line 12
        require DateTime/Duration.pm called at D:\s\DateTime\blib\lib/DateTime.pm line 14
        DateTime::BEGIN() called at D:\s\DateTime\blib\lib/DateTime.pm line 14
        eval {...} called at D:\s\DateTime\blib\lib/DateTime.pm line 14
        require DateTime.pm called at t/00load.t line 8
        main::BEGIN() called at t/00load.t line 8
        eval {...} called at t/00load.t line 8
        eval 'package main;
BEGIN { ${^WARNING_BITS} = $args[-1] if defined $args[-1] }
#line 8 t/00load.t
use DateTime @{$args[0]};
1;
' called at C:/perl-5.38.0-1310-lhm/lib/Test/More.pm line 1056
        Test::More::_eval("package main;\x{a}BEGIN { \${^WARNING_BITS} = \$args[-1] if defined"..., ARRAY(0x2e26044), "UUUUUUUUUUUUUUUUUUUU") called at C:/perl-5.38.0-1310-lhm/lib/Test/More.pm line 1031
        Test::More::use_ok("DateTime") called at t/00load.t line 8
</code>

I recall there was a problem with some module (it might have been namespace::autoclean, as you've suggested) trying to access B::Hooks::OP::Check in a way that didn't port to Windows.
I intervened manually, and that's probably where the dependency on Sub::Identify got missed.
When I get a chance, I'll hunt down  the offending module, and report the issue to the appropriate forum (if that hasn't already been done).

Thanks for the reply; sorry for the noise.
Closing this in anticipation of it being an error on my part.

Cheers,
Rob
