### ISSUE TITLE
last_day_of_month suggestion

### ISSUE THREAD

**Issue by earthman1** [houseabsolute/DateTime.pm#60]
While last_day_of_month is available as a constructor, there are times when I need to know the last day of the current month stored in the DateTime object, and constructing a new object has higher overhead than simply calculating it. While DateTime performs the calculation internally, it is not exposed to users of the class, except in the form of the constructor. 

Time::Piece offers this calculation as $tp->month_last_day(). Following the same naming convention, I'd like to propose the following code addition to DateTime.pm:
`sub month_last_day {`
`	Carp::carp('month_last_day() is a read-only accessor') if @_ > 1;`
`	return $_[0]->_month_length( $_[0]->{local_c}{year}, $_[0]->{local_c}{month} );`
`}`

**Comment by autarch** [comment]
This feels a little weird to me since DateTime objects generally only know about the object itself, not about "things sort of related" to the object.

It also seems like a premature optimization. There's already a way to get the info. Do you need the last day of month so often that constructing a new object is really slowing down your application?

**Comment by earthman1** [comment]
I'm not sure why you would think it was weird to provide access to this calculation. The DateTime class itself uses _month_length() in at least 3 functions internally to perform date-related calculations, notably without instantiating a new object each time. Why would it? That would be inefficient. :-)

With respect to performance, I am doing the end of month calculation inside of a loop, as part of a larger multinational scheduling calculation, looping over thousands of schedules, to determine if a specified time in the user's timezone is a meeting in their schedule. It is possible to move the end of month calculation outside the loop, reducing the number of calls _somewhat_, but it twists the code in knots, decreasing legibility. Or I could use the undocumented DateTime functionality `$date->_month_length($date->year,$date->month);` which is a tiny bit slower than the code I provided above, and could break at any time due to internal changes to the DateTime class. I could copy the _month_length function and its dependencies from DateTime.pm into my codebase, and give up the possibility of any improvements that might come in an upgrade to the DateTime module. I was hoping a four line change to provide access to an existing, useful and relevant date calculation would be better than the alternatives I'd explored.

Here is the timing code I used to test the efficiency:
`#!/usr/bin/perl -W`
`use strict;`
`use feature qw{say};`
`use Time::HiRes qw(gettimeofday tv_interval);`
`use DateTime;`
`my $maxiter=1000000;`
`my $date = DateTime->now();`
`my $t0 = [gettimeofday];`
`foreach my $i (0 .. $maxiter) { $date->month_last_day; } #implies the new function has been implemented :-)`
`my $t1 = [gettimeofday];`
`foreach my $i (0 .. $maxiter) { DateTime->last_day_of_month(year => $date->year, month => $date->month); }`
`my $t2 = [gettimeofday];`
`say "$maxiter iterations: function took    " . tv_interval($t0, $t1) . " seconds";`
`say "$maxiter iterations: constructor took " . tv_interval($t1, $t2) . " seconds";`
`say "constructor was " . tv_interval($t1, $t2)/tv_interval($t0, $t1) . " times slower";`

The output in my environment is:
`1000000 iterations: function took    0.939967 seconds`
`1000000 iterations: constructor took 55.524525 seconds`
`constructor was 59.0707173762483 times slower`

**Comment by earthman1** [comment]
I have spent more time considering your concern about the class providing information about "things sort of related" to the object. I understand your concern that the last day of the month stored in the object is not direct information about the date stored in the object. I would relate the `month_last_day()` function that I am proposing to the `leap_seconds()` method that is already provided, insofar as the information returned is only about "things sort of related" to the object.

To be honest, what I am calculating at that point in my application is not specifically what the last day of the month is, but rather whether the date stored in the DateTime object falls on the last day of the month. That is actually direct information about the date stored in the object. Limited by the information I have available at that moment, I am instead comparing the object's day with the day that falls at the end of that month, to see if they are the same. Providing an additional boolean `is_end_of_month()` method would not be different in character from the `is_leap_year()` method the class already provides.

I believe, based on search results from Google, that I am not the first person to struggle with how to perform this calculation, which DateTime is already performing internally, and could resolve quite easily.

Thanks!

**Comment by autarch** [comment]
Adding an `is_end_of_month` method definitely makes sense. Another thing I'd consider would be a class method of the form `DateTime->last_day_of_month($year, $month)`. It'd return a number indicating the last day of the month (1-31).

**Comment by autarch** [comment]
I note that `last_day_of_month` would just be a renamed `_month_length`.

**Comment by chansen** [comment]
I think it would be a API/design mistake to add more class methods, why clutter the DateTime class with a routine that doesn't need to be in the class/package?

An instance method that returns the length of the month would IMHO be a more appropriate.

```
$days = $dt->length_of_year;
$days = $dt->length_of_quarter;
$days = $dt->length_of_month;

$is_last_day_of_year  = $dt->day_of_year  == $dt->length_of_year;
$is_last_day_of_month = $dt->day_of_month == $dt->length_of_month;

sub at_last_day_of_month {
    my ($dt) = @_;
    return $dt->set(day => $dt->length_of_month);
}

```

**Comment by autarch** [comment]
@preaction I don't think adding a new mutator adds much since we already have `DateTime->last_day_of_month` as a constructor.

I made a PR to just add an `is_last_day_of_month` method. As @earthman1 noted, this is very similar to the existing `is_leap_year` method in concept.

**Comment by autarch** [comment]
#63

**Comment by autarch** [comment]
Done in v1.44
