### ISSUE TITLE
Extension to iso8601() to include time zone?

### ISSUE THREAD

**Issue by showaltb** [houseabsolute/DateTime.pm#61]
I need to write ISO8601 datetime strings in JSON messages being passed between multiple applications with multiple languages. I need to include time zone offset information to avoid ambiguous timestamps.

I note the following difficulties:

* `DateTime`'s `iso8601' method does not include time zone (as documented)
* I can append time zone by doing something like:

        $dt->iso8601 . $dt->strftime('%z')

    this gives something like `2017-08-09T15:17:28-0400`. Unfortunately, this is not parseable by `DateTime::Format::ISO8601`, as it strictly needs a colon (`-04:00`) (this has been patched, but not released as far as I can tell; see https://rt.cpan.org/Public/Bug/Display.html?id=108082).
* `DateTime::Format::ISO8601` does not have a `format_datetime` method. This makes it unsuitable to be used as a formatter that can be passed to `$dt->set_formatter()`

Would you be open to a patch to `DateTime` that would add an option to the `iso8601` method that would include time zone offset?

* If the offset is zero (UTC), append `Z`
* Otherwise, append in the form `+hh:mm` or `-hh:mm`

Example:

    $dt->iso8601       # "2017-08-09T15:17:28" (current format)
    $dt->iso8601(1)    # "2017-08-09T15:17:28-04:00" (with offset)

This would not affect any existing code, because the current `iso8601` method does not accept any arguments.

**Comment by preaction** [comment]
There's an open PR to add `format_datetime` to DateTime::Format::ISO8601: https://github.com/jhoblitt/DateTime-Format-ISO8601/pull/2

**Comment by autarch** [comment]
I'd much prefer to see the PR noted above applied. I'll nag that maintainer of the ISO8601 formatter. I suspect he's not doing Perl any more so that module may need a new maintainer.

**Comment by showaltb** [comment]
That sounds fine, thanks.
