### ISSUE TITLE
Can't locate DateTime/TimeZone/OlsonDB/Change.pm

### ISSUE THREAD

**Issue by lijinfeng2011** [houseabsolute/DateTime.pm#67]
./cpan install DateTime
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.56)
Reading '/root/.cpan/Metadata'
  Database was generated on Thu, 23 Nov 2017 05:17:02 GMT
Running install for module 'DateTime'
CPAN: Digest::SHA loaded ok (v5.95)
CPAN: Compress::Zlib loaded ok (v2.069)
Checksum for /root/.cpan/sources/authors/id/D/DR/DROLSKY/DateTime-1.44.tar.gz ok
CPAN: File::Temp loaded ok (v0.2304)
'YAML' not installed, will not store persistent state
CPAN: CPAN::Meta::Requirements loaded ok (v2.140)
CPAN: Parse::CPAN::Meta loaded ok (v1.4417)
CPAN: CPAN::Meta loaded ok (v2.150005)
CPAN: Module::CoreList loaded ok (v5.20160506)
Configuring D/DR/DROLSKY/DateTime-1.44.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for DateTime
Writing MYMETA.yml and MYMETA.json
  DROLSKY/DateTime-1.44.tar.gz
  /data/scripts/nices/perl/bin/perl Makefile.PL -- OK
Running make for D/DR/DROLSKY/DateTime-1.44.tar.gz
cp lib/DateTime/PPExtra.pm blib/lib/DateTime/PPExtra.pm
cp lib/DateTime.pm blib/lib/DateTime.pm
cp lib/DateTime/LeapSecond.pm blib/lib/DateTime/LeapSecond.pm
cp lib/DateTime/Duration.pm blib/lib/DateTime/Duration.pm
cp lib/DateTime/Helpers.pm blib/lib/DateTime/Helpers.pm
cp lib/DateTime/Conflicts.pm blib/lib/DateTime/Conflicts.pm
cp lib/DateTime/Infinite.pm blib/lib/DateTime/Infinite.pm
cp lib/DateTime/PP.pm blib/lib/DateTime/PP.pm
cp lib/DateTime/Types.pm blib/lib/DateTime/Types.pm
Running Mkbootstrap for DateTime ()
chmod 644 "DateTime.bs"
"/data/scripts/nices/perl/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- DateTime.bs blib/arch/auto/DateTime/DateTime.bs 644
"/data/scripts/nices/perl/bin/perl" "/data/scripts/nices/perl/lib/5.24.0/ExtUtils/xsubpp"  -typemap '/data/scripts/nices/perl/lib/5.24.0/ExtUtils/typemap'  DateTime.xs > DateTime.xsc
mv DateTime.xsc DateTime.c
cc -c   -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"1.44\" -DXS_VERSION=\"1.44\" -fPIC "-I/data/scripts/nices/perl/lib/5.24.0/x86_64-linux/CORE"   DateTime.c
rm -f blib/arch/auto/DateTime/DateTime.so
cc  -shared -O2 -L/usr/local/lib -fstack-protector DateTime.o  -o blib/arch/auto/DateTime/DateTime.so  \
              \

chmod 755 blib/arch/auto/DateTime/DateTime.so
  DROLSKY/DateTime-1.44.tar.gz
  /usr/bin/make -- OK
Running make test
"/data/scripts/nices/perl/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- DateTime.bs blib/arch/auto/DateTime/DateTime.bs 644
PERL_DL_NONLAZY=1 "/data/scripts/nices/perl/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-report-prereqs.t .... #
 Versions for all modules listed in MYMETA.json (including optional ones):

 === Configure Requires ===

     Module               Want Have
     -------------------- ---- ----
     Dist::CheckConflicts 0.02 0.11
     ExtUtils::MakeMaker   any 7.24

 === Configure Suggests ===

     Module      Want    Have
     -------- ------- -------
     JSON::PP 2.27300 2.27300

 === Build Requires ===

     Module              Want Have
     ------------------- ---- ----
     ExtUtils::MakeMaker  any 7.24

 === Test Requires ===

     Module                    Want     Have
     ------------------------ ----- --------
     CPAN::Meta::Check        0.011    0.014
     CPAN::Meta::Requirements   any    2.140
     ExtUtils::MakeMaker        any     7.24
     File::Spec                 any     3.63
     Storable                   any     2.56
     Test::Fatal                any    0.014
     Test::More                0.96 1.302062
     Test::Warnings           0.005    0.026
     utf8                       any     1.19

 === Test Recommends ===

     Module         Want     Have
     ---------- -------- --------
     CPAN::Meta 2.120900 2.150005

 === Runtime Requires ===

     Module                     Want  Have
     -------------------------- ---- -----
     Carp                        any  1.40
     DateTime::Locale           1.06  1.10
     DateTime::TimeZone         2.02  2.07
     Dist::CheckConflicts       0.02  0.11
     POSIX                       any  1.65
     Params::ValidationCompiler 0.13  0.16
     Scalar::Util                any  1.46
     Specio                     0.18  0.30
     Specio::Declare             any  0.30
     Specio::Exporter            any  0.30
     Specio::Library::Builtins   any  0.30
     Specio::Library::Numeric    any  0.30
     Specio::Library::String     any  0.30
     Try::Tiny                   any  0.27
     XSLoader                    any  0.24
     base                        any  2.23
     integer                     any  1.01
     namespace::autoclean       0.19  0.28
     overload                    any  1.26
     parent                      any 0.234
     strict                      any  1.11
     warnings                    any  1.36
     warnings::register          any  1.04

t/00-report-prereqs.t .... ok
t/00load.t ............... 1/?
   Failed test 'use DateTime;'
   at t/00load.t line 6.
     Tried to use 'DateTime'.
     Error:  Can't locate DateTime/TimeZone/OlsonDB/Change.pm in @INC (you may need to install the DateTime::TimeZone::OlsonDB::Change module) (@INC contains: /root/.cpan/build/DateTime-1.44-uYlKPY/blib/lib /root/.cpan/build/DateTime-1.44-uYlKPY/blib/arch /data/scripts/nices/perl/lib/site_perl/5.24.0/x86_64-linux /data/scripts/nices/perl/lib/site_perl/5.24.0 /data/scripts/nices/perl/lib/5.24.0/x86_64-linux /data/scripts/nices/perl/lib/5.24.0 .) at /data/scripts/nices/perl/lib/site_perl/5.24.0/DateTime/TimeZone.pm line 15, <DATA> line 1.
 BEGIN failed--compilation aborted at /data/scripts/nices/perl/lib/site_perl/5.24.0/DateTime/TimeZone.pm line 15, <DATA> line 1.
 Compilation failed in require at /root/.cpan/build/DateTime-1.44-uYlKPY/blib/lib/DateTime.pm line 17, <DATA> line 1.
 BEGIN failed--compilation aborted at /root/.cpan/build/DateTime-1.44-uYlKPY/blib/lib/DateTime.pm line 17, <DATA> line 1.
 Compilation failed in require at t/00load.t line 6, <DATA> line 1.
 BEGIN failed--compilation aborted at t/00load.t line 6, <DATA> line 1.
 Looks like you failed 1 test of 1.
t/00load.t ............... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
t/01sanity.t ............. Can't locate DateTime/TimeZone/OlsonDB/Change.pm in @INC (you may need to install the DateTime::TimeZone::OlsonDB::Change module) (@INC contains: /root/.cpan/build/DateTime-1.44-uYlKPY/blib/lib /root/.cpan/build/DateTime-1.44-uYlKPY/blib/arch /data/scripts/nices/perl/lib/site_perl/5.24.0/x86_64-linux /data/scripts/nices/perl/lib/site_perl/5.24.0 /data/scripts/nices/perl/lib/5.24.0/x86_64-linux /data/scripts/nices/perl/lib/5.24.0 .) at /data/scripts/nices/perl/lib/site_perl/5.24.0/DateTime/TimeZone.pm line 15,<DATA> line 1.
BEGIN failed--compilation aborted at /data/scripts/nices/perl/lib/site_perl/5.24.0/DateTime/TimeZone.pm line 15, <DATA> line 1.
Compilation failed in require at /root/.cpan/build/DateTime-1.44-uYlKPY/blib/lib/DateTime.pm line 17, <DATA> line 1.
BEGIN failed--compilation aborted at /root/.cpan/build/DateTime-1.44-uYlKPY/blib/lib/DateTime.pm line 17, <DATA> line 1.
Compilation failed in require at t/01sanity.t line 6, <DATA> line 1.
BEGIN failed--compilation aborted at t/01sanity.t line 6, <DATA> line 1.
t/01sanity.t ............. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
t/02last-day.t ........... Can't locate DateTime/TimeZone/OlsonDB/Change.pm in @INC (you may need to install the DateTime::TimeZone::OlsonDB::Change module) (@INC contains: /root/.cpan/build/DateTime-1.44-uYlKPY/blib/lib /root/.cpan/build/DateTime-1.44-uYlKPY/blib/arch /data/scripts/nices/perl/lib/site_perl/5.24.0/x86_64-linux /data/scripts/nices/perl/lib/site_perl/5.24.0 /data/scripts/nices/perl/lib/5.24.0/x86_64-linux /data/scripts/nices/perl/lib/5.24.0 .) at /data/scripts/nices/perl/lib/site_perl/5.24.0/DateTime/TimeZone.pm line 15,<DATA> line 1.
BEGIN failed--compilation aborted at /data/scripts/nices/perl/lib/site_perl/5.24.0/DateTime/TimeZone.pm line 15, <DATA> line 1.
Compilation failed in require at /root/.cpan/build/DateTime-1.44-uYlKPY/blib/lib/DateTime.pm line 17, <DATA> line 1.
BEGIN failed--compilation aborted at /root/.cpan/build/DateTime-1.44-uYlKPY/blib/lib/DateTime.pm line 17, <DATA> line 1.
Compilation failed in require at t/02last-day.t line 7, <DATA> line 1.
BEGIN failed--compilation aborted at t/02last-day.t line 7, <DATA> line 1.

**Comment by autarch** [comment]
I'm not sure what's going on here but I'm inclined to think the problem is on your system. If the DateTime-TimeZone distro was actually missing a module I would have heard about this much earlier.

**Comment by lijinfeng2011** [comment]
You're right.
I lost the file at the same time on a lot of machines, which led to my wrong judgment.
