### ISSUE TITLE
Handling dates

### ISSUE THREAD

**Issue by sciurius** [houseabsolute/DateTime.pm#82]
I use DateTime for all kinds of date/time handling.

Sometimes I have to deal with dates, year/month/day, without time. DateTime can handle this. Hoewever, as far as DateTime concerns, a date without time is just a date with time 00:00:00. So I can not tell from the DateTime object that it was created to represent a date only.

After reading the docs and the wiki I started to wonder whether I'm overlooking something trivial. Is it possible for DateTime to represent a date without time and distinguish this from a date with time 00:00:00?

Thanks for the great module.

**Comment by preaction** [comment]
To my knowledge, it is not: A DateTime object represents a point in time, and a date isn't a point in time. In previous projects, I ended up using [Date::Tiny](https://metacpan.org/pod/Date::Tiny) objects to represent dates, and DateTime objects to represent date/times.

**Comment by autarch** [comment]
Yes, what @preaction said. I'm going to close this since it's not something that can really be fixed in DateTime. If I ever write DateTime2 (not likely) I would redo it as a suite of classes, one of which would be for dates without times.

**Comment by sciurius** [comment]
Well, I thought the only thing required would be an attribute that the user can set and read, and that persists across the various operations...
Maybe signaling an error when a add/subtract with granularity less than day is attempted.
