### ISSUE TITLE
day_of_year in constructor parameters

### ISSUE THREAD

**Issue by gaiederer** [houseabsolute/DateTime.pm#88]
would be nice to have a constructor like
  * new DateTime(year=>$yr, **doy=>$doy**, ...).

We use year-day_of_year quite a lot when dealing with satellite data sets.

**Comment by autarch** [comment]
You mean like this? https://metacpan.org/pod/DateTime#DateTime-%3Efrom_day_of_year(-...-)

**Comment by gaiederer** [comment]
Thanks. Don't know how I missed it.
