### ISSUE TITLE
Rounding problems with nanosecond CLDR formatting

### ISSUE THREAD

**Issue by eserte** [houseabsolute/DateTime.pm#89]
The following test script fails on many systems (mostly linux; I cannot reproduce the problem on freebsd):
```
#!/usr/bin/perl

use strict;
use warnings;
use DateTime;
use Test::More 'no_plan';

my $dt = DateTime->now;
$dt->set_nanosecond(10);
is '00000001000000', $dt->format_cldr('SSSSSSSSSSSSSS');

__END__
```
Output is:
```
not ok 1
#   Failed test at /tmp/dt.pl line 10.
#          got: '00000001000000'
#     expected: '00000000999999'
1..1
# Looks like you failed 1 test of 1.
```

Probably this is caused by perl and/or POSIX::floor inaccuracies:
```
$ perl -MPOSIX=floor -E 'say floor(10/10**-5)'     
999999
```

This is possibly the problem for the test failures seen in the DateTime::Format::CLDR module (@maros: FYI): https://rt.cpan.org/Public/Bug/Display.html?id=124691

Just an idea: avoiding the division and the negative exponent could help here. So if the exponent would be negative, then make it positive and multiply instead of divide:
```
$ perl -MPOSIX=floor -E 'say floor(10*10**5)' 
1000000
```
It seems that this way the internal SV stays as an IV; otherwise it would be turned into a NV, possibly causing problems.

Proposed code change for `_format_nanosecs` (pseudo code, untested):
```
my $exponent = 9 - $precision;
my $formatted_ns = ($exponent < 0 ? $self->{rd_nanosecs} * 10**-$exponent : $self->{rd_nanosecs} / 10**$exponent);
... floor($formatted_ns) ...
```

**Comment by autarch** [comment]
Fixed in v1.51. Thanks for the report!
