### ISSUE TITLE
Wrong (?) values after substraction

### ISSUE THREAD

**Issue by Infarch** [houseabsolute/DateTime.pm#92]
Substracting one date from another, I see some ambiguous result. Have a look at the code:
`
	my $dt1 = DateTime->new(
		year => 2000,
		month => 3,
		day => 5,
	);
	my $dt2 = DateTime->new(
		year => 2000,
		month => 3,
		day => 25,
	);
	my $duration = $dt2 - $dt1;
	print $duration->days; # the result is 6!
`
I get '6' instead of 20, but getting days via function '$duration->in_units' works well, as well as '$duration->delta_days'. May be I'm missing something but such result looks as a bug.

**Comment by autarch** [comment]
No, this is by design. Most people will probably find the `in_units` method most useful for getting information out of a duration. See https://metacpan.org/pod/DateTime::Duration#$dur-%3Ein_units(-...-) and https://metacpan.org/pod/DateTime#How-DateTime-Math-Works for more details.
