### ISSUE TITLE
Math issue with add(months) and February?

### ISSUE THREAD

**Issue by francoisbeaulieu** [houseabsolute/DateTime.pm#99]
Hi,

Testing DateTime 1.51 on both Mac and Linux, the following code gets me the same, erroneous result:

```
my $dt = DateTime->new(
    year       => 2020,
    month      => 1,
    day        => 31,
    hour       => 23,
    minute     => 59,
    second     => 59,
    nanosecond => 000000000,
    time_zone  => 'UTC',
);

$dt->add(months=>1);
say $dt->strftime("%F %T %Z");
```
Results in:
> 2020-03-02 23:59:59 UTC

Rather than February 29th. 2019 gives March 3rd, so it's not a leap year thing.

**Comment by autarch** [comment]
See the [`DateTime::Duration` docs on the `end_of_month` parameter(https://metacpan.org/pod/DateTime::Duration#DateTime::Duration-%3Enew(-...-)) for an exaplanation of what's going on and how you can change it.
